# Prometheus configuration for Email Assist monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Email Assist Backend metrics
  - job_name: 'email-assist-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  # Redis metrics  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 10s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://frontend:80/health
        - http://backend:3001/health
        - http://nginx:80/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Email Assist custom metrics
  - job_name: 'email-assist-metrics'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

# Recording rules for aggregated metrics
recording_rules:
  - name: email_assist_aggregations
    rules:
      # Email processing rate
      - record: email_assist:email_processing_rate
        expr: rate(email_assist_emails_processed_total[5m])
      
      # Error rate
      - record: email_assist:error_rate
        expr: rate(email_assist_errors_total[5m]) / rate(email_assist_requests_total[5m])
      
      # Response time percentiles
      - record: email_assist:response_time_p95
        expr: histogram_quantile(0.95, rate(email_assist_request_duration_seconds_bucket[5m]))
      
      - record: email_assist:response_time_p99
        expr: histogram_quantile(0.99, rate(email_assist_request_duration_seconds_bucket[5m]))

# Alerting rules
alerting_rules:
  - name: email_assist_alerts
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: email_assist:error_rate > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: High error rate detected
          description: "Error rate is {{ $value }} for the last 2 minutes"
      
      # Service down
      - alert: ServiceDown
        expr: up{job=~"email-assist-.*"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 30 seconds"
      
      # High memory usage
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes{name=~"email-assist-.*"} / container_spec_memory_limit_bytes{name=~"email-assist-.*"}) > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: "Container {{ $labels.name }} is using {{ $value | humanizePercentage }} of memory"
      
      # High CPU usage
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{name=~"email-assist-.*"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage
          description: "Container {{ $labels.name }} CPU usage is {{ $value | humanizePercentage }}"
      
      # Database connection issues
      - alert: DatabaseConnectionFailure
        expr: email_assist_database_connections_failed_total > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Database connection failures
          description: "{{ $value }} database connection failures in the last minute"
      
      # Disk space low
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Low disk space
          description: "Filesystem {{ $labels.mountpoint }} has only {{ $value | humanizePercentage }} space left"